name: Azure Kubernetes Clusters
on:
  workflow_dispatch:

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - name: Run KQL query
        uses: azure/pipelines@v1
        with:
          task: azure-monitor-log-analytics-query
          query: |
            let avgMemRssBytes = avg(mem_rss_bytes);
            | summarize avgMemRssBytes = avg(mem_rss_bytes)
          resource-group: 'my-resource-group'
          output-format: table
